# Generated by Django 4.1.6 on 2023-02-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myEventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='venue name')),
                ('addrise', models.CharField(max_length=120, verbose_name='address ')),
                ('zip_code', models.CharField(max_length=30, verbose_name='zip code')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email_addriss', models.EmailField(max_length=60, verbose_name='email')),
                ('websit', models.URLField(max_length=120, verbose_name='web site')),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='event name')),
                ('event_date', models.DateTimeField(verbose_name='event date')),
                ('manager', models.CharField(max_length=60)),
                ('Description', models.TextField(blank=True)),
                ('attendess', models.ManyToManyField(blank=True, to='main.myeventuser')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.venue')),
            ],
        ),
    ]
