# Generated by Django 4.1.6 on 2023-02-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='email_addriss',
            field=models.EmailField(blank=True, max_length=60, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='websit',
            field=models.URLField(blank=True, max_length=120, verbose_name='web site'),
        ),
    ]
