# Generated by Django 4.1.7 on 2023-02-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.TextField(blank=True),
        ),
    ]
