# Generated by Django 4.1.7 on 2023-02-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_review_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_event',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
    ]
